name: Code Style
on: [pull_request]

permissions: {}

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    permissions:
      code-quality: write
    
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.2"

      - name: Install dependencies
        run: composer update --dev --no-interaction --prefer-dist --no-progress --no-suggest --ansi

      - name: Run phpcs
        run: ./vendor/bin/phpcs -q --report=checkstyle src

  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: phpstan

      - name: Install dependencies
        run: composer update --dev --no-interaction --prefer-dist --no-progress --no-suggest --ansi

      - name: Run phpstan
        run: phpstan analyse --no-progress